### ISSUE TITLE
master is behind two releases

### ISSUE THREAD

**Issue by intelfx** [matrix-org/syutil#2]
master branch (points to 8753ac7a0f4fa998749c680fe4625231ec3cbb6e) is behind releases 0.0.4 (6305779bffbbd1886ec4a66eedf9615267e19611) and 0.0.5 (a65b4a25718c71f4abaca2bfca5a312d219d67b5).

**Comment by NegativeMjark** [comment]
Ah, I forgot to a "git push" when releasing 0.0.4 and 0.0.5. The master branch should be up to date now. Thanks for pointing it out.
